[package]
name = "wu-api"
version = "0.0.1-beta.2"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2024"

[dependencies]
wu = { path = "../wu" }
kern = { version = "1.8.3", features = ["tls"] }
jzon = "0.12.5"
mysql = "27.0.0"
